#When we count, we usually do it in base 10. That means that each place in a number can hold one of ten values, 0-9. In binary we count in base two, where each place can hold one of two values: 0 or 1.
#In Python, you can write numbers in binary format by starting the number with 0b.
#, FOR keep in same line it work only in codeacadmy console
print (0b1,)    #1
print (0b10,)   #2
print(0b11,)  #3
print(0b100,)  #4
print(0b101,)  #5
print(0b110,) #6
print(0b111)   #7
print(0b1000)  #8
print(0b1001) #9
print(0b1010) #10
print("******")
print(0b1 + 0b11)
print(0b11 * 0b11)
